/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2015-01-12 14:24:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cust.dew.util.MyProperties;
import java.util.*;
import com.cust.dew.dao.impl.*;
import com.cust.dew.vo.*;
import com.cust.dew.util.Pagination;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>公共界面</title>\r\n");
      out.write("<link href=\"css/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/ddsmoothmenu.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/commodity.css\">\r\n");
      out.write("<!-- 显示商品 -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath );
      out.write("mb611/slider/scripts/jquery-1.7.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"templatemo_body_wrapper\">\r\n");
      out.write("\t\t<div id=\"templatemo_wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"templatemo_header\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"cleaner\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END of templatemo_header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"templatemo_menubar\">\r\n");
      out.write("\t\t\t\t<div id=\"top_nav\" class=\"ddsmoothmenu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(basePath);
      out.write("commodity!index.action\" >首页</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(basePath);
      out.write("requirement.action?mypage=first&jhpage=0\">求购信息</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(basePath);
      out.write("commodity!IT.action?mypage=first&jhpage=0\">数码产品</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(basePath);
      out.write("commodity!book.action?mypage=first&jhpage=0\">书籍</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(basePath);
      out.write("commodity!bycycle.action?mypage=first&jhpage=0\">单车</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(basePath);
      out.write("map.action\">地图</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<br style=\"clear: left\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- end of ddsmoothmenu -->\r\n");
      out.write("\t\t\t\t<div id=\"templatemo_search\">\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" value=\" \" name=\"keyword\" id=\"keyword\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"keyword\" onFocus=\"clearText(this)\"\r\n");
      out.write("\t\t\t\t\t\t\tonblur=\"clearText(this)\" class=\"txt_field\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" name=\"Search\" value=\" \" alt=\"Search\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"searchbutton\" title=\"Search\" class=\"sub_btn\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END of templatemo_menubar -->\r\n");
      out.write("\t\t\t<!-- 主页 -->\r\n");
      out.write("\t\t\t<div id=\"templatemo_main\">\r\n");
      out.write("\t\t\t    <div id=\"main_left\">\r\n");
      out.write("\t\t\t       <h3 align=\"center\" id=\"lh\">商品分类</h3>\r\n");
      out.write("\t\t\t       <ul>\r\n");
      out.write("\t\t\t          <!-- <li>&nbsp;</li> -->\r\n");
      out.write("\t\t\t          <li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;电脑专区</a></li>\r\n");
      out.write("\t\t\t\t      <li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;手机通讯</a></li>\r\n");
      out.write("\t\t\t\t      <li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;书籍资料</a></li>\r\n");
      out.write("\t\t\t\t      <li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;服装服饰</a></li>\r\n");
      out.write("\t\t\t\t      <li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数码产品</a></li>\r\n");
      out.write("\t\t\t\t      <li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;生活电器</a></li>\r\n");
      out.write("\t\t\t       </ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div id=\"main_middle\"></div>\r\n");
      out.write("\t\t\t    <div id=\"main_right\">\r\n");
      out.write("\t\t\t\t<table id=\"commoditytable\">\r\n");
      out.write("\t\t\t\t\t");
					    
						//分页
						String mypage = null;//分页   
						int jhpage = 0; 
						if(session.getAttribute("mypage") != null){
							 mypage = (String)session.getAttribute("mypage");
						}else{
							mypage = "first";
						}
						System.out.println("mypage:" + mypage);
						
					    Pagination p = new Pagination();
					    if(mypage.equals("next")){		
					    	Pagination.setAllSize(16);    							    	
						    Pagination.setPage( Integer.parseInt(request.getAttribute("jhpage").toString())+ Pagination.getAllSize());		
						    jhpage =  Pagination.getPage();//第三次用的	    
					        
					    }else if(mypage.equals("past")){
					    	Pagination.setAllSize(16);    
					    	System.out.println(Integer.parseInt(request.getAttribute("jhpage").toString()));
						    Pagination.setPage( Integer.parseInt(request.getAttribute("jhpage").toString())- Pagination.getAllSize());		
						    jhpage =  Pagination.getPage();//第三次用的	
						    System.out.println("jhpage" + jhpage);
					    }else if(mypage.equals("first")){
					    	Pagination.setPage(0);
					    	Pagination.setAllSize(16);
					    } 					    					   
					    
						  CommodityDBDao cd = DaoFactory.getCommodityDBDao();
						  List<Commodity>  peList = cd.queryCommodity();						  
						  System.out.println("mark:"+peList.size());	  												  											      
					      
					      for(int i = 0;i <peList.size();i = i + MyProperties.CommodityWightAcount){	 
						
      out.write("\r\n");
      out.write("\t\t\t\t\t                <tr id=\"commoditytr\" >\r\n");
      out.write("\t\t\t\t\t\t");

									for(int j = 0 ;j < MyProperties.CommodityWightAcount; j++){
							        	Commodity com ;
							        	if(j < peList.size() ){
							        	    if(peList.size() < 16){
							        			if(j < peList.size() - i){
							        				com =(Commodity)peList.get(i + j);
							        				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t <td id=\"commoditytd\">\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <div id=\"commoditydiv\">\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <img alt=\"\" src=\"");
      out.print(basePath);
      out.write("imageLaction.action?type=");
      out.print(MyProperties.co );
      out.write("&imageLocation=");
      out.print(com.getCoimg());
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t ");
 
																	      String coname = com.getConame();
																	      if(coname.length() > 4 ){
																	    	  
																	    	  coname = coname.substring(0,4) + "...";
																	      }
																	    
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"cspan1\">商品名：");
      out.print(coname);
      out.write("</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"cspan2\">价格：");
      out.print(com.getCoprise());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t     </a>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t     </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

															        			}
							        		}else{
								        		 com =(Commodity)peList.get(i + j);
															        		 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"commoditytd\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"commoditydiv\">\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <img alt=\"\" src=\"");
      out.print(basePath);
      out.write("imageLaction.action?type=");
      out.print(MyProperties.co );
      out.write("&imageLocation=");
      out.print(com.getCoimg());
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    ");
 
																	      String coname = com.getConame();
																	      if(coname.length() > 4 ){
																	    	  
																	    	  coname = coname.substring(0,4) + "...";
																	      }
																	    
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"cspan1\">商品名：");
      out.print(coname);
      out.write("</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"cspan2\">价格：");
      out.print(com.getCoprise());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t     </a>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t");

								        	}							        								        	 
							        	  
							        	}
							        	
							        	
							        }
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						    
							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"pagination\">\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(basePath);
      out.write("commodity!index.action?mypage=past&jhpage=");
      out.print(jhpage );
      out.write("\">上一页</a>\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(basePath);
      out.write("commodity!index.action?mypage=next&jhpage=");
      out.print(jhpage );
      out.write("\">下一页</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sidebar\" class=\"float_l\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\" class=\"float_r faqs\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"templatemo_footer\"></div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"display: none\">\r\n");
      out.write("\t\t<script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540'\r\n");
      out.write("\t\t\tlanguage='JavaScript' charset='gb2312'></script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
