/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.20
 * Generated at: 2015-08-05 01:10:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajaxsendresponse_002dget_002dpost;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajax_002dpost_002dsendresponse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>密码</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar xmlHttpRequest = null;\r\n");
      out.write("\tfunction ajaxCallback() {\r\n");
      out.write("\t\tif (xmlHttpRequest.readyState == 4) {//readyState的四种状态值 \r\n");
      out.write("\t\t\talert(xmlHttpRequest.status);\r\n");
      out.write("\t\t\tif (xmlHttpRequest.status == 200 || xmlHttpRequest.status == 304) {\r\n");
      out.write("\t\t\t\t// 获取服务器的值,500内部错误，200连接成功\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"divcheck\").innerHTML = xmlHttpRequest.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction ajaxSubmit() {\r\n");
      out.write("\t\tvar name = document.getElementById(\"name\").value;\r\n");
      out.write("\t\tvar ps = document.getElementById(\"ps\").value;\r\n");
      out.write("\t\tvar cps = document.getElementById(\"cps\").value;\r\n");
      out.write("\r\n");
      out.write("\t\tif (window.ActiveXObject) {\r\n");
      out.write("\t\t\txmlHttpRequest = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t} else if (window.XMLHttpRequest) {\r\n");
      out.write("\t\t\txmlHttpRequest = new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (null != xmlHttpRequest) {\r\n");
      out.write("\t\t\txmlHttpRequest.onreadystatechange = ajaxCallback;\r\n");
      out.write("\t\t\txmlHttpRequest.open(\"POST\", \"/ajaxresponse\", true);\r\n");
      out.write("\t\t\txmlHttpRequest.setRequestHeader(\"Content-Type\",\r\n");
      out.write("\t\t\t\t\t\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\txmlHttpRequest.send(\"name=\" + name + \"&ps=\" + ps + \"&cps=\" + cps);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t<table border=\"2\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>用户名</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"name\" value=\"\" id=\"name\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>密码:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"ps\" id=\"ps\" value=\"\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>确认密码:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"cps\" id=\"cps\" value=\"\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"button\" value=\"提交\" onclick=\"ajaxSubmit()\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div id=\"divcheck\"></div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
