/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2015-01-12 14:26:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 登录页面 -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>登录页面 </title>\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("css/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("css/ddsmoothmenu.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("css/login.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"templatemo_body_wrapper\">\r\n");
      out.write("<div id=\"templatemo_wrapper\">\r\n");
      out.write(" \r\n");
      out.write("\t<div id=\"templatemo_header\">\r\n");
      out.write("    \t\r\n");
      out.write("        <div class=\"cleaner\"></div>\r\n");
      out.write("    </div> <!-- END of templatemo_header -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"templatemo_menubar\">\r\n");
      out.write("    \t<div id=\"top_nav\" class=\"ddsmoothmenu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"../index.jsp\">首页</a></li>\r\n");
      out.write("                <li><a href=\"products.jsp\">求购信息</a></li>\r\n");
      out.write("                <li><a href=\"about.jsp\">数码产品</a></li>\r\n");
      out.write("                <li><a href=\"faqs.jsp\" >书籍</a></li>\r\n");
      out.write("                <li><a href=\"checkout.jsp\">单车</a></li>\r\n");
      out.write("                <li><a href=\"contact.jsp\">地图</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <br style=\"clear: left\" />\r\n");
      out.write("        </div> <!-- end of ddsmoothmenu -->\r\n");
      out.write("        <div id=\"templatemo_search\">\r\n");
      out.write("            <form action=\"#\" method=\"get\">\r\n");
      out.write("              <input type=\"text\" value=\" \" name=\"keyword\" id=\"keyword\" title=\"keyword\" onfocus=\"clearText(this)\" onblur=\"clearText(this)\" class=\"txt_field\" />\r\n");
      out.write("              <input type=\"submit\" name=\"Search\" value=\" \" alt=\"Search\" id=\"searchbutton\" title=\"Search\" class=\"sub_btn\"  />\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- END of templatemo_menubar -->\r\n");
      out.write("    \r\n");
      out.write("    \t<div id=\"templatemo_main\">\r\n");
      out.write("\t\t\t<div id = \"login_left\">\r\n");
      out.write("\t\t\t    <div id=\"divcheck\"></div>\r\n");
      out.write("\t\t\t\t<div id = \"login_title\">用户登录</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<div id = \"login_suggestion\"></div>\r\n");
      out.write("\t\t\t\t<div id = \"login_text\">\r\n");
      out.write("\t\t\t\t\t<div id = \"login_username\">用户名：</div>\r\n");
      out.write("\t\t\t\t\t<div id = \"login_password\">密码：</div>\r\n");
      out.write("\t\t\t\t\t<div id = \"login_affirm\">验证码：</div>\r\n");
      out.write("\t\t\t\t</div><!-- End of login_text -->\r\n");
      out.write("\t\t\t\t<div id = \"login_input\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" name=\"login\" action=\"");
      out.print(basePath);
      out.write("login.action\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"author\" name=\"author\"class=\"required input_field\" /> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\"name=\"password\" id=\"password\" class=\"input_field\" /> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"yanzheng1\" id=\"yanzheng1\"class=\"input_field\" /> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"yanzheng2\" id=\"yanzheng2\"class=\"input_field\" /> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" id=\"submit\" value=\"登录\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- End of login_left  -->\r\n");
      out.write("\t\t\t<div id = \"login_right\"></div>\r\n");
      out.write("    \t</div> <!-- END of templatemo_main -->\r\n");
      out.write("    \r\n");
      out.write("</div> <!-- END of templatemo_wrapper -->\r\n");
      out.write("</div> <!-- END of templatemo_body_wrapper -->\r\n");
      out.write("<div style=\"display:none\"><script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
